name: telegraf
services:
  telegraf:
    image: telegraf:alpine
    container_name: layer8-telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 4317:4317
    environment:
      - INFLUXDB_URL_TELEGRAF=${INFLUXDB_URL_TELEGRAF}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"